{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bindery.dataClaimName" . }}
  labels:
    {{- include "bindery.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.persistence.library.enabled (not .Values.persistence.library.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bindery.libraryClaimName" . }}
  labels:
    {{- include "bindery.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.library.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.library.size | quote }}
  {{- with .Values.persistence.library.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
