{{- if not .Values.bindery.plugins.tokenSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindery.pluginTokenSecretName" . }}
  labels:
    {{- include "bindery.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bindery.plugins.tokenSecret.key }}: {{ randAlphaNum 48 | quote }}
{{- end }}
